"""create backend workflow schema

Revision ID: ad0606803e8d
Revises:
Create Date: 2026-09-12 14:52:01.654274
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ad0606803e8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('idempotency_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_sha256', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_id'),
    sa.UniqueConstraint('actor_id', 'operation', 'idempotency_key')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('scenario_id', sa.String(length=128), nullable=True),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_graph_run_id', sa.String(length=64), nullable=True),
    sa.Column('current_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('current_result_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_owner_id'), 'tasks', ['owner_id'], unique=False)
    op.create_table('graph_runs',
    sa.Column('graph_run_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('started_revision', sa.Integer(), nullable=False),
    sa.Column('effective_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_interrupt_issue_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('graph_run_id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index(op.f('ix_graph_runs_task_id'), 'graph_runs', ['task_id'], unique=False)
    op.create_table('quotes',
    sa.Column('quote_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.String(length=128), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_id')
    )
    op.create_index(op.f('ix_quotes_task_id'), 'quotes', ['task_id'], unique=False)
    op.create_table('requirements',
    sa.Column('requirement_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('task_revision', sa.Integer(), nullable=False),
    sa.Column('requirement_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    op.create_index(op.f('ix_requirements_task_id'), 'requirements', ['task_id'], unique=False)
    op.create_table('task_revisions',
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('request_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('task_id', 'revision')
    )
    op.create_index(op.f('ix_task_revisions_task_id'), 'task_revisions', ['task_id'], unique=False)
    op.create_table('workflow_artifacts',
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('task_revision', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=True),
    sa.Column('parent_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('quote_id', sa.String(length=64), nullable=True),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('graph_run_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index(op.f('ix_workflow_artifacts_artifact_type'), 'workflow_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_workflow_artifacts_document_id'), 'workflow_artifacts', ['document_id'], unique=False)
    op.create_index(op.f('ix_workflow_artifacts_graph_run_id'), 'workflow_artifacts', ['graph_run_id'], unique=False)
    op.create_index(op.f('ix_workflow_artifacts_quote_id'), 'workflow_artifacts', ['quote_id'], unique=False)
    op.create_index(op.f('ix_workflow_artifacts_task_id'), 'workflow_artifacts', ['task_id'], unique=False)
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('quote_id', sa.String(length=64), nullable=False),
    sa.Column('quote_version', sa.Integer(), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.quote_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_index(op.f('ix_documents_quote_id'), 'documents', ['quote_id'], unique=False)
    op.create_index(op.f('ix_documents_task_id'), 'documents', ['task_id'], unique=False)
    op.create_table('issues',
    sa.Column('issue_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('graph_run_id', sa.String(length=64), nullable=False),
    sa.Column('quote_id', sa.String(length=64), nullable=True),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('answer_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_revision', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('resolved_revision', sa.Integer(), nullable=True),
    sa.Column('answered_by', sa.String(length=128), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['graph_run_id'], ['graph_runs.graph_run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id'),
    sa.UniqueConstraint('graph_run_id', 'issue_type', 'quote_id', 'field_name')
    )
    op.create_index(op.f('ix_issues_graph_run_id'), 'issues', ['graph_run_id'], unique=False)
    op.create_index(op.f('ix_issues_quote_id'), 'issues', ['quote_id'], unique=False)
    op.create_index(op.f('ix_issues_task_id'), 'issues', ['task_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('graph_run_id', sa.String(length=64), nullable=False),
    sa.Column('issue_id', sa.String(length=64), nullable=True),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('task_revision', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['graph_run_id'], ['graph_runs.graph_run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_graph_run_id'), 'jobs', ['graph_run_id'], unique=False)
    op.create_index(op.f('ix_jobs_task_id'), 'jobs', ['task_id'], unique=False)
    op.create_table('document_executions',
    sa.Column('document_execution_id', sa.String(length=64), nullable=False),
    sa.Column('graph_run_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('calls_used', sa.Integer(), nullable=False),
    sa.Column('max_calls', sa.Integer(), nullable=False),
    sa.Column('parsed_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('batch_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('review_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graph_run_id'], ['graph_runs.graph_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_execution_id'),
    sa.UniqueConstraint('graph_run_id', 'document_id')
    )
    op.create_index(op.f('ix_document_executions_document_id'), 'document_executions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_executions_graph_run_id'), 'document_executions', ['graph_run_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_executions_graph_run_id'), table_name='document_executions')
    op.drop_index(op.f('ix_document_executions_document_id'), table_name='document_executions')
    op.drop_table('document_executions')
    op.drop_index(op.f('ix_jobs_task_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_graph_run_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_issues_task_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_quote_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_graph_run_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_documents_task_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_quote_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_workflow_artifacts_task_id'), table_name='workflow_artifacts')
    op.drop_index(op.f('ix_workflow_artifacts_quote_id'), table_name='workflow_artifacts')
    op.drop_index(op.f('ix_workflow_artifacts_graph_run_id'), table_name='workflow_artifacts')
    op.drop_index(op.f('ix_workflow_artifacts_document_id'), table_name='workflow_artifacts')
    op.drop_index(op.f('ix_workflow_artifacts_artifact_type'), table_name='workflow_artifacts')
    op.drop_table('workflow_artifacts')
    op.drop_index(op.f('ix_task_revisions_task_id'), table_name='task_revisions')
    op.drop_table('task_revisions')
    op.drop_index(op.f('ix_requirements_task_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_quotes_task_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_graph_runs_task_id'), table_name='graph_runs')
    op.drop_table('graph_runs')
    op.drop_index(op.f('ix_tasks_owner_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
