"""Member B's quote parsing, model adapter, and evidence boundary."""

from .contracts import (
    AdapterEnvironment,
    AdapterOutputMode,
    BoundingBox,
    CandidateProducer,
    DocumentContext,
    EvidenceSource,
    ExtractionBatch,
    ExtractionRun,
    NormalizationEvent,
    Origin,
    ParsedInput,
    QuoteFieldCandidate,
    SourceCitation,
    SourceKind,
    ValidationStatus,
)
from .corrections import apply_candidate_correction
from .criticality import (
    ALWAYS_CRITICAL_FIELDS,
    CONDITIONAL_CRITICAL_FIELDS,
    NON_CRITICAL_FIELDS,
    CriticalityContext,
    resolve_criticalities,
)
from .human_review import create_review_event
from .readiness import require_downstream_ready
from .review import model_failed_envelope, review_extraction_batch
from .review_contracts import (
    CorrectionAction,
    CorrectionEvent,
    EffectiveCriticality,
    FieldReviewDecision,
    FieldReviewFinding,
    HumanReviewAction,
    ReviewEnvelope,
    ReviewEvent,
    ReviewReason,
    ReviewSeverity,
    ReviewStatus,
)

__all__ = [
    "AdapterEnvironment",
    "AdapterOutputMode",
    "BoundingBox",
    "CandidateProducer",
    "DocumentContext",
    "EvidenceSource",
    "ExtractionBatch",
    "ExtractionRun",
    "NormalizationEvent",
    "Origin",
    "ParsedInput",
    "QuoteFieldCandidate",
    "SourceCitation",
    "SourceKind",
    "ValidationStatus",
    "ALWAYS_CRITICAL_FIELDS",
    "CONDITIONAL_CRITICAL_FIELDS",
    "NON_CRITICAL_FIELDS",
    "CriticalityContext",
    "CorrectionAction",
    "CorrectionEvent",
    "EffectiveCriticality",
    "FieldReviewDecision",
    "FieldReviewFinding",
    "HumanReviewAction",
    "ReviewEnvelope",
    "ReviewEvent",
    "ReviewReason",
    "ReviewSeverity",
    "ReviewStatus",
    "apply_candidate_correction",
    "create_review_event",
    "model_failed_envelope",
    "require_downstream_ready",
    "resolve_criticalities",
    "review_extraction_batch",
]
